{
 "title": "KubeInvaders Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Chaos jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(increase(chaos_jobs_node_count[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Killed pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "deleted_pods_total" }
   ]
  },
  {
   "title": "Chaos jobs against nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "chaos_node_jobs_total" }
   ]
  },
  {
   "title": "Killed pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(increase(deleted_namespace_pods_count[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Chaos jobs count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "chaos_jobs_node_count", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Killed pods count",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "deleted_namespace_pods_count", "legendFormat": "{{namespace}}" }
   ]
  }
 ]
}